sudo: false
language: java
cache:
  directories:
    - $HOME/.m2
install:
  - echo 'skipped'
matrix:
  - jdk: openjdk8
    env: CODECOV="true"
    script: travis_retry ./scripts/run_no_prep_tests.sh
  - jdk: openjdk11
    env: CODECOV="false"
    script: travis_retry ./scripts/run_no_prep_tests.sh
  - jdk: openjdk8
    script:
      - travis_retry ./mvnw install -Dmaven.test.skip=true -Dmaven.javadoc.skip=true --no-transfer-progress
      - travis_retry ./mvnw duplicate-finder:check --no-transfer-progress
after_success:
  - test "$CODECOV" = "true" && bash <(curl -s https://codecov.io/bash)
