title: Java Slack SDK
description: Slack SDK for Java supports all public Slack platform functionality in a Java idiomatic way. The SDK is completely written in Java, so that developers can use this SDK in any JVM language, including Kotlin, Groovy, and Scala without any hurdles.
description_ja: Slack SDK for Java は Java らしいアプローチで全ての Slack プラットフォームの公開機能をサポートする公式 SDK です。この SDK は全て Java で書かれており、開発者はこの SDK を Java だけでなく Kotlin、Groovy、Scala といった JVM 言語でも問題なく利用できます。
markdown: kramdown

baseurl: /java-slack-sdk
url: https://slack.dev

sdkLatestVersion: 1.25.0
okhttpVersion: 4.10.0
slf4jApiVersion: 1.7.36
kotlinVersion: 1.7.10
springBootVersion: 2.7.3
compatibleMicronautVersion: 3.x
quarkusVersion: 2.12.0.Final
helidonVersion: 2.5.0
javaxWebsocketApiVersion: 1.1
tyrusStandaloneClientVersion: 1.19
