title: Java Slack SDK
description: Slack SDK for Java supports all public Slack platform functionality in a Java idiomatic way. The SDK is completely written in Java, so that developers can use this SDK in any JVM language, including Kotlin, Groovy, and Scala without any hurdles.
description_ja: Slack SDK for Java は Java らしいアプローチで全ての Slack プラットフォームの公開機能をサポートする公式 SDK です。この SDK は全て Java で書かれており、開発者はこの SDK を Java だけでなく Kotlin、Groovy、Scala といった JVM 言語でも問題なく利用できます。
markdown: kramdown

baseurl: /java-slack-sdk
url: https://slack.dev

sdkLatestVersion: 1.1.2
kotlinVersion: 1.3.72
springBootVersion: 2.3.1.RELEASE
compatibleMicronautVersion: 2.x
quarkusVersion: 1.6.0.Final
helidonVersion: 1.4.5