sdkLatestVersion: 1.43.0
okhttpVersion: 4.10.0
slf4jApiVersion: 1.7.36
kotlinVersion: 1.7.21
helidonVersion: 2.5.0
javaxWebsocketApiVersion: 1.1
springBootVersion: 3.0.0
compatibleMicronautVersion: 3.x
quarkusVersion: 2.12.0.Final
tyrusStandaloneClientVersion: 1.20
tyrusStandaloneClientV2Version: 2.2.0
jakartaWebsocketApiVersion: 2.2.0
